apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # This name matches the 'mongodb-service' in your app manifest
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017