apiVersion: v1
kind: Service
metadata:
  name: clausebusters-app-service
spec:
  selector:
    app: clausebusters-app
  type: LoadBalancer # Exposes your application to the internet
  ports:
    - protocol: TCP
      port: 80 # External port for the load balancer
      targetPort: 4000 # Your application's internal port