name: CD Pipeline

on:
  push:
    branches:
      - main           
      - feature/*      
jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  

      # Set up Heroku CLI
      - name: Set up Heroku CLI
        uses: akshnz/heroku-cli-action@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}  
      # Login to Heroku
      - name: Login to Heroku
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login ${HEROKU_API_KEY}" >> ~/.netrc
          echo "  password ${HEROKU_API_KEY}" >> ~/.netrc

      # Push the code to Heroku
      - name: Deploy to Heroku
        run: git push https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main
        